description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: sh
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        cache: 'yarn'
        node-version-file: '.node-version'
    - run: yarn install --immutable --mode=skip-build
      shell: sh
