stages:
  - install_dependencies
  - build
  - deploy
  - test

variables:
  BUILD_PATH: public
  DEPLOY_ROOT: /var/www

install_dependencies:
  artifacts:
    paths:
      - node_modules
  cache:
    key:
      files:
        - package.json
  image: buildkite/puppeteer@sha256:f4c9e3973bf90276a14bd62e3805ef3e126a92f1c50344bd5c9ebca1aa671434
  script:
    - npm install
  stage: install_dependencies
  tags:
    - docker-node

build:
  artifacts:
    expire_in: 1 day
    paths:
      - $BUILD_PATH
  image: buildkite/puppeteer@sha256:f4c9e3973bf90276a14bd62e3805ef3e126a92f1c50344bd5c9ebca1aa671434
  script:
    - npm run build
  stage: build
  tags:
    - docker-node

build env:
  artifacts:
    reports:
      dotenv: .env
  dependencies: []
  except:
    - master
  script:
    - MAX_CN_LENGTH=64
    - SUBDOMAIN=$(echo $CI_COMMIT_REF_SLUG | cut -c 1-$(($MAX_CN_LENGTH - $(echo .qa.$DEPLOY_HOST | wc -m))))
    - echo HOSTNAME=$SUBDOMAIN.qa.$DEPLOY_HOST >> .env
  stage: build
  tags:
    - docker-node

.deploy: &deploy
  dependencies:
    - build
  environment:
    url: https://$HOSTNAME
  script:
    - envsubst < deploy/site.bootstrap.template.conf > /etc/nginx/sites-available/$HOSTNAME.conf
    - ln -s -fn ../sites-available/$HOSTNAME.conf /etc/nginx/sites-enabled/$HOSTNAME.conf
    - sudo nginx -s reload
    - sudo letsencrypt certonly --domain $HOSTNAME --domain www.$HOSTNAME
    - envsubst < deploy/site.template.conf > /etc/nginx/sites-available/$HOSTNAME.conf
    - ln -s -fn $(pwd)/$BUILD_PATH $DEPLOY_PATH
    - sudo nginx -s reload
  stage: deploy
  tags:
    - www-server

deploy:
  <<: *deploy
  environment:
    name: production
    url: https://$HOSTNAME
  only:
    - master
  variables:
    DEPLOY_PATH: $DEPLOY_ROOT/$DEPLOY_HOST
    HOSTNAME: $DEPLOY_HOST

deploy-branch:
  <<: *deploy
  dependencies:
    - build
    - build env
  environment:
    name: $CI_COMMIT_REF_NAME
    on_stop: stop
    url: https://$HOSTNAME
  only:
    - branches
  except:
    - master
  variables:
    DEPLOY_PATH: $DEPLOY_ROOT/$HOSTNAME

stop:
  dependencies:
    - build env
  environment:
    action: stop
    name: $CI_COMMIT_REF_NAME
  except:
    - master
  script:
    - rm -rf $DEPLOY_PATH
    - rm /etc/nginx/sites-{available,enabled}/$HOSTNAME.conf
    - sudo letsencrypt revoke --cert-path /etc/letsencrypt/live/$HOSTNAME/cert.pem
    - sudo nginx -s reload
  stage: deploy
  tags:
    - www-server
  variables:
    CONTAINER_TAG: $CI_COMMIT_REF_SLUG
    GIT_STRATEGY: none

  when: manual
