rules:
  react/jsx-boolean-value: warn
  react/jsx-closing-bracket-location: warn
  react/jsx-curly-spacing: [warn, never]
  react/jsx-fragments: [warn, element]
  react/jsx-indent-props: [warn, 2]
  react/jsx-no-undef: error
  react/jsx-uses-react: warn
  react/jsx-wrap-multilines: warn
  react/no-direct-mutation-state: error
  react/no-multi-comp: warn
  react/no-unescaped-entities: [error, {forbid: ['>', '}']}]
  react/no-unknown-property: error
  react/sort-prop-types: warn
settings:
  react:
    version: detect
