parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - react-hooks
rules:
  react/jsx-boolean-value: warn
  react/jsx-closing-bracket-location: warn
  react/jsx-curly-spacing: [warn, never]
  react/jsx-fragments: [warn, element]
  react/jsx-indent-props: [warn, 2]
  react/jsx-no-undef: error
  react/jsx-uses-react: warn
  react/jsx-uses-vars: warn
  react/jsx-wrap-multilines: warn
  react/no-direct-mutation-state: error
  react/no-multi-comp: warn
  react/no-unknown-property: error
  react/react-in-jsx-scope: error
  react/sort-prop-types: warn
settings:
  react:
    version: 16.8
