description: Provides Common Setup for Workflows Dependent on Playwright
name: setup-playwright

runs:
  using: composite
  steps:
    - run: |
        PLAYWRIGHT_VERSION=`yarn info playwright-core --name-only | cut -d @ -f 2 | cut -d : -f 2`
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      id: playwright-version
      shell: sh
    - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      id: playwright-binaries
      env:
        PLAYWRIGHT_VERSION: env.PLAYWRIGHT_VERSION
      with:
        key: ${{ runner.os }}-playwright-binaries-${{ env.PLAYWRIGHT_VERSION }}
        path: ~/.cache/ms-playwright
    - run: yarn playwright install --with-deps
      if: steps.playwright-binaries.outputs.cache-hit != 'true'
      shell: sh
