description: Provides Common Setup for Workflows Dependent on Playwright
name: setup-playwright

runs:
  using: composite
  steps:
    - run: |
        PLAYWRIGHT_VERSION=`yarn info playwright-core --name-only | cut -d @ -f 2 | cut -d : -f 2`
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      id: playwright-version
      shell: sh
    - uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      id: playwright-binaries
      with:
        key: ${{ runner.os }}-playwright-binaries-${{ env.PLAYWRIGHT_VERSION }}
        path: ~/.cache/ms-playwright
    - run: yarn playwright-core install --with-deps
      if: steps.playwright-binaries.outputs.cache-hit != 'true'
      shell: sh
