name: typescript

on:
  pull_request:
    paths-ignore:
      - '**/*.ts'
      - '**/*.tsx'
      - .github/actions/setup-node/**
      - .github/workflows/typescript.yml
      - package.json
      - tsconfig.json
      - yarn.lock

jobs:
  typescript:
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'Skipped'
